### ISSUE TITLE
Adding Hours and Minutes to Time Picker

### ISSUE THREAD

**Issue by oroncarty-toast** [OzcanAlasalvar/DatePicker#40]
Is there any way to add hr and min text to the picker as shown below?
<img width="391" alt="Screenshot 2024-02-20 at 9 10 22 PM" src="https://github.com/ozcanalasalvar/picker/assets/148129791/f21b74b8-561a-4a37-b83f-c5d1458cbe9a">

**Comment by ozcanalasalvar** [comment]
unfortunately this feature is not available
