### ISSUE TITLE
Bug in release build

### ISSUE THREAD

**Issue by hkmonumeena** [OzcanAlasalvar/DatePicker#41]
Fatal Exception: java.lang.NoSuchMethodError
No static method items$default(Landroidx/compose/foundation/lazy/LazyListScope;ILkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function4;ILjava/lang/Object;)V in class Landroidx/compose/foundation/lazy/LazyListScope; or its super classes (declaration of 'androidx.compose.foundation.lazy.LazyListScope' appears in /data/app/~~dvpxDbu2j4qrjTulliy9vw==/com.ruchitech.quicklinkcaller-Ax3zZoB_MjrjwlLaM9JrBQ==/base.apk)

**Comment by ozcanalasalvar** [comment]
Your project should support jetpack compose, otherwise you will encounter this warning
