### ISSUE TITLE
WheelTimePicker startTime is not work

### ISSUE THREAD

**Issue by OCNYang** [OzcanAlasalvar/DatePicker#42]
look code:

https://github.com/ozcanalasalvar/picker/blob/393c275d1c335ea9af396ded2492b3624b18f29a/datepicker/src/main/java/com/ozcanalasalvar/datepicker/compose/timepicker/WheelTimePicker.kt#L91

**Comment by Vinny94051** [comment]
yeap, true

**Comment by osamaastal** [comment]
How to fix it?

**Comment by Vinny94051** [comment]
> How to fix it?

This guy create a fork with fix. Here is the fix commit link https://github.com/chinmaydash007/picker/commit/a51c08bb5c8ec77de50f0a373957a6d3393ab991
