### ISSUE TITLE
It is not working in nested scroll view

### ISSUE THREAD

**Issue by ChetanPatelSS** [OzcanAlasalvar/DatePicker#5]
Add this method in WheelView.java
@Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        // Stop ScrollView from getting involved once you interact with the View
        if (ev.getActionMasked() == MotionEvent.ACTION_DOWN) {
            ViewParent p = getParent();
            if (p != null){
                p.requestDisallowInterceptTouchEvent(true);
            }
        }
        return super.onInterceptTouchEvent(ev);
    }

**Comment by OzcanAlasalvar** [comment]
Thank you for your feedback. I made related issue and publish a new release. You can start to use with nested  scroll enable version with version number "1.0.8".
